name: PHPUnit Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1  # Change this to your desired PHP version

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: composer exec phpunit tests
